pub static LINK_TEMPLATE: &str = r#"
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link rel="canonical" href="{url}" />
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta http-equiv="refresh" content="0;url={url}" />
    </head>
    <body>
        <h1>Redirecting...</h1>
          <a href="{url}">Click here if you are not redirected.</a>
          <script>location.href="{url}"</script>
    </body>
</html>
"#;

pub static LINK_INDEX: &str = r#"
<!doctype html>
<html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">

      <title>A static url shortener</title>
      <meta name="description" content="This site was generated by https://github.com/adriantombu/mubo">
    </head>

    <body>
        <ul>
            {{for link in links}}
                <li><a href="./r/{link.key}/">{link.url}</a></li>
            {{endfor}}
        </ul>
    </body>
</html>
"#;
